### ISSUE TITLE
UI for Viewing Text Posts

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#10]
### Related User Stories
**1. As an author I want to make public posts.
10. As an author, posts I make can be in simple plain text
25. As an author, I want to be able to use my web-browser to author my posts**

### Description / Notes
- UI for viewing a post (GET get the public post)
- This task could be limited to displaying text posts and creating image posts could be separated into a separate issue if needed but likely to not necessary

### Tasks
- [ ] UI for a viewing a post (GET get the public post)
- [ ] Test UI
- [ ] Test being able to send a GET request to Django

**Comment by jmmxp** [comment]
Currently all done, images work as well. Just need support for viewing markdown.

**Comment by raysarinas** [comment]
Viewing markdown is now issue #80
