### ISSUE TITLE
Frontend Axios Wrapper

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#148]
### Related User Stories
**28. As a server admin, I don't want to do heavy setup to get the posts of my author's friends
**

Rough example from Justin:
```
wrapper.get(url) // use these instead of axios
wrapper.post(url) 

function get(url) {
  for each key in nodes
    if url contains(key)
      make the request using credentials
}
```

**Comment by jmmxp** [comment]
Done, wrapper was created and used in #167, and request URLs were updated in #174

**Comment by jmmxp** [comment]
Made updates to the wrapper in #182.
