### ISSUE TITLE
Setup Connectivity and Node Model/Endpoint

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#149]
### Related User Stories
**38. As a server admin, I want to be able to add nodes to share with
39. As a server admin, I want to be able to remove nodes and stop sharing with them.
40. As a server admin, I can limit nodes connecting to me via authentication.
41. As a server admin, node to node connections can be authenticated with HTTP Basic Auth
42. As a server admin, I can disable the node to node interfaces for connections that are not authenticated!**

**Comment by jmmxp** [comment]
Done, #147, #160, #177,  and #182.
