### ISSUE TITLE
Host Images on Server

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#15]
### Related User Stories
**5. As a server admin, images can be hosted on my server.**

### Description / Notes
- Host images on server
- Probably involves a database-related task
- Need to discuss this as this issue may be part of, or may block issue #13 

### Tasks
- [x] Verify images can be hosted on server
- [x] Test that images can be hosted on server

**Comment by jmmxp** [comment]
This has been done since we modelled content as a TextField. Closing issue.
