### ISSUE TITLE
Using UUIDs for IDs

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#16]
We should be using UUIDs for author_ids and have appropriate tests for how they're being used. Team may need to discuss further if necessary.

Instead of: 
```python
_id = models.CharField(max_length=LONG_CHAR_LENGTH, unique=True)
```

should use something like:
```python
import uuid
from django.db import models

_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

https://docs.djangoproject.com/en/3.1/ref/models/fields/#uuidfield

**Comment by jmmxp** [comment]
From my understanding, if we make this into a UUID field then we no longer have a way to easily make API requests to a server at the given ID (nor provide this functionality for other servers).

**Comment by raysarinas** [comment]
> From my understanding, if we make this into a UUID field then we no longer have a way to easily make API requests to a server at the given ID (nor provide this functionality for other servers).

Can you elaborate more on what you mean? What would be the alternative?
