### ISSUE TITLE
Add Timestamps to Posts

### ISSUE THREAD

**Issue by raysarinas** [CMPUT404W21T02/group-project#95]
### Related User Stories
**16. As an author, I want to post posts to my "stream."
37. As an author, I should be able to browse the public posts of everyone.**

### Description / Notes
Just display timestamps on each Post. Only small change(s) required in `PostListItem`

**Comment by ChrisChrisLoLo** [comment]
Out of curiosity, is this a `should have`, or a `could have`?

**Comment by raysarinas** [comment]
> Out of curiosity, is this a `should have`, or a `could have`?

I guess it's just a `could have`? I opened up the ticket since you mentioned it's something we should have. I don't think this issue is non-trivial. Could probably be finished quickly.
